#!/usr/bin/perl

use Time::Local;

my $t = ($ARGV[0] || time);

#  0    1    2     3     4    5     6     7     8
#($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = localtime(time);


if ($t =~ /^\d+$/) {
  my @a = localtime($t);
  print sprintf('%04d-%02d-%02d %02d:%02d:%02d', $a[5]+1900, $a[4]+1, $a[3], $a[2], $a[1], $a[0]), "\n";
} elsif ($t =~ /^(\d{4})[-\/](\d?\d)[-\/](\d?\d) (\d\d):(\d\d):(\d\d)/) {
  my ($yr, $mo, $dy, $hr, $mn, $sc) = ($1, $2, $3, $4, $5, $6);
  $yr -= 1900;
  $mo -= 1;
  print timelocal($sc, $mn, $hr, $dy, $mo, $yr), "\n";
} else {
  die "bad format for time";
}
